language: c
dist: bionic
before_script:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb
  - sudo dkp-pacman -Syu
  - sudo dkp-pacman --noconfirm -S switch-dev
  - source /etc/profile.d/devkit-env.sh
script:
  - make dist
deploy:
  provider: releases
  api_key:
    secure: gGHUpVLyjh8+H8z3kcbhbk9sh1E5wFKUVWCIjmu05VzElmQB7DC/4IRkiVy7UIbSwG62+ou0XLglEqTQgAyrgDAYQkST0s9Ie152a2n45BDZyoqclIW9GhkfQFVIFedpUXCiCOoxsLeOeVSgAU1++srw7J3NioFabOWePhfxYIAXw3JCreZ/ZoxiyAX0O5FbS3z1LP9wjx3p+tUT2xyyaYDVTIXIBKv9NvOEt4c3Qoo9bGJOqa3IxwcXQ7i1qW/emTcudVjGUofd3UaVBAlvCcsSMdBwjkM1pmo8P8SrMfAX0GJKTR8LFhMJw4hDlpjg9mqzMr4UNOcSqmbySbhUifhgvoKPNLa+vj63KXmIHNxFmehBpIxu6ynkP/Oo6OncKmefxO1z3ZxpkP/8ZS6o+rjYVT5ptdMDuQ0TeV54bAXsA8KuDJQyDUln8r70ejmBjMn1GexwGp0eKUAqGuYwsLL9FNoUzCHTX8F63VydQisc2MATSkvGjotyu1jFLt6F49ah/wO6fh0X/6qrLibEKkZ9umlkLsL+GZeYc5+aV+BnjnikRz0c+pdGaKSZi7Q06/wVFGzty4TlOKHNN96vVMcvN99jH4T6iYVKVmazEZGWf2U2gY7POa2KxhMD6hsBbJjohoruKalmnElyH8QxgU1sZUSKA6HP9gI/9U0wjCc=
  file: sys-gdbstub.zip
  overwrite: true
  skip_cleanup: true
  on:
    repo: mossvr/sys-gdbstub
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]*.[0-9]*.*$
