name: Build

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  create:
    tags:
      - "v*"

jobs:
  build:
    name: ubuntu-20.04(ubuntu-latest)
    runs-on: ubuntu-20.04(ubuntu-latest)
    container: devkitpro/devkita64:20210726

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          make -j2
          make dist

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: sys-gdbstub
          path: out/*
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: sys-gdbstub.zip
